services:
  reactapp:
    build:
      context: ./
      args:
        - MY_UID=${MY_UID}
        - MY_GID=${MY_GID}
        - PORT_VITE=${PORT_VITE}
    env_file:
      - .env
    volumes:
      - ..:/home/appuser
      - .:/home/appuser/front
    ports:
      - ${PORT_VITE}:${PORT_VITE}
    command: ["/bin/bash", "-c", "/home/appuser/front/build.sh"]
